table.insert(controls, {Name = "ais_reconnect",ControlType = "Button",ButtonType = "Trigger",PinStyle = "Output",UserPin = true})--,Icon = "refresh"})
table.insert(controls, {Name = "connect_disabled",ControlType = "Button",ButtonType = "Toggle",Color = "Red",Text = "Disabled"})
table.insert(controls, {Name = "IPAddress",ControlType = "Text"})
table.insert(controls, {Name = "Port",ControlType = "Knob",ControlUnit = "Integer",Min = 0,Max = 65535})
table.insert(controls, {Name = "Username",ControlType = "Text"})
table.insert(controls, {Name = "Password",ControlType = "Text"})
table.insert(controls, {Name = "Status",ControlType = "Indicator",IndicatorType = "Status",PinStyle = "Output",UserPin = true})
table.insert(controls, {Name = "SendString",ControlType = "Text",PinStyle = "Input",UserPin = true})
table.insert(controls, {Name = "feedback",ControlType = "Indicator",IndicatorType = "Text",PinStyle = "Output",UserPin = true})
table.insert(controls, {Name = "debug",ControlType = "Text",PinStyle = "Output",UserPin = true})
table.insert(controls, {Name = "ClearFeedback",ControlType = "Button",ButtonType = "Trigger",Text = "Clear"})
table.insert(controls,{Name ="Queue",ControlType = "Text",UserPin = true,PinStyle = "Output",Count = 1})
table.insert(controls,{Name ="ClearQueue",ControlType = "Button",ButtonType = "Trigger",UserPin = true,PinStyle = "Both",Count = 1})